network:
  version: 2
  ethernets:
    uplink:
      match:
        name: "en*"
      dhcp4: false
      wakeonlan: true
  bridges:
    br0:
      interfaces:
        - uplink
      dhcp4: true
      parameters:
        stp: false
        forward-delay: 0
