hypervisors:
  vars:
    # default vars for all hosts
    # override at host-specific vars
    ansible_user: ubuntu
    ansible_become: True
    has_gpu: False
    gpu_pci_ids: []

  hosts:
    nvidia-1.local:
      has_gpu: True
      gpu_pci_ids:
        - 10de:2702 # 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD103 [GeForce RTX 4080 SUPER] [10de:2702] (rev a1)
        - 10de:22bb # 01:00.1 Audio device [0403]: NVIDIA Corporation Device [10de:22bb] (rev a1)
      root_disks:
        - /dev/disk/by-id/nvme-CT1000P3PSSD8_2233E6567FBE-part3
        - /dev/disk/by-id/nvme-SHPP41-1000GM_AJD1N595713201V0H_1-part1

    sparkle-1.local:
      has_gpu: True
      gpu_pci_ids:
        - 8086:e20c # 03:00.0 VGA compatible controller [0300]: Intel Corporation Device [8086:e20c]
        - 8086:e2f7 # 04:00.0 Audio device [0403]: Intel Corporation Device [8086:e2f7]
      root_disks:
        - /dev/disk/by-id/nvme-SHPP41-2000GM_SND4N423512104I6G_1-part3

